//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPT
    {
        public DEPT()
        {
            this.EMP = new HashSet<EMP>();
        }
    
        public decimal DEPTNO { get; set; }
        public string DNAME { get; set; }
        public Nullable<int> LOC { get; set; }
    
        public virtual CITY CITY { get; set; }
        public virtual ICollection<EMP> EMP { get; set; }
    }
}
