//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class EmpDeptEntities : DbContext
    {
        public EmpDeptEntities()
            : base("name=EmpDeptEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CITY> CITY { get; set; }
        public DbSet<DEPT> DEPT { get; set; }
        public DbSet<EMP> EMP { get; set; }
        public DbSet<EVERYTHING> EVERYTHING { get; set; }
    
        [EdmFunction("EmpDeptEntities", "GETEMP")]
        public virtual IQueryable<GETEMP_Result> GETEMP(Nullable<int> empno)
        {
            var empnoParameter = empno.HasValue ?
                new ObjectParameter("empno", empno) :
                new ObjectParameter("empno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GETEMP_Result>("[EmpDeptEntities].[GETEMP](@empno)", empnoParameter);
        }
    
        public virtual int GETNAME(Nullable<int> id, ObjectParameter name)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GETNAME", idParameter, name);
        }
    }
}
